[General]
ArcfsDirectory = 'F:\MHGU\mhmodtools-by-dasding\arcfs'
ChunkDirectory = 'D:\MHWI Mods\chunk'
NativeDirectory = 'F:\SteamLibrary\steamapps\common\Monster Hunter World\nativePC'
Theme = 'Deep Dark'

[Optimization.AllowMultipleReferences]
KV128 = true
KV32 = true
KV8 = true

[Utility]
AutoAdjustKeyFrames = true