[General]
ChunkDirectory = 'D:\MHWI Mods\chunk'
NativeDirectory = 'C:\Program Files\Steam\steamapps\common\Monster Hunter World\nativePC'
Theme = 'Dracula'

[Optimization.AllowMultipleReferences]
KV128 = true
KV32 = true
KV8 = true